name: project

services:
  project-php:
    container_name: project-php
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ../:/var/www

  project-nginx:
    image: nginx:latest
    container_name: project-nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  project-postgres:
    image: library/postgres:10.14
    container_name: project-postgres
    environment:
      POSTGRES_DB: "db_test_api"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "54320:5432"
    volumes:
      - project_postgres_data10:/var/lib/postgresql/data10

volumes:
  project_postgres_data10: {}